[package]
name = "chronicle"
version = "0.1.0"
edition = "2021"
description = "Activity tracking daemon with input and window monitoring"
authors = ["Jerry Yang <efjerryyang@outlook.com>"]
license = "MIT"

[[bin]]
name = "chronicle"
path = "src/main.rs"

[dependencies]
# Use local vendor winshift with richer callbacks (ActiveWindowInfo)
winshift = "0.0.3" # { path = "../vendor/winshift-rs" }
uiohook-rs = "0.2" # { path = "../vendor/uiohook-rs" }
clap = { version = "4.4", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"
chrono = { version = "0.4", features = ["serde"] }
ctrlc = "3.4"
thiserror = "1.0"
log = "0.4"
env_logger = "0.11"
anyhow = "1.0"
dirs = "5.0"
sysinfo = "0.35"
libc = "0.2"
ringbuf = "0.4"
tokio = { version = "1.0", features = ["full"] }
rusqlite = { version = "0.30", features = ["bundled"] }
async-trait = "0.1"
size-of = { version = "0.1", features = ["derive", "std", "chrono"] }
once_cell = "1.19"
ratatui = { version = "0.29.0", features = ["crossterm"] }
crossterm = "0.29.0"
config = "0.13"
